server.port=8081
spring.application.name=back-end

spring.mongodb.uri=mongodb+srv://ashandhanushka16_db_user:mashi123@cluster0.sfworcl.mongodb.net/salon_db?retryWrites=true&w=majority&appName=Cluster0

application.security.jwt.secret-key=c29tZXZlcnlzZWNyZXRrZXl0aGF0aXNsb25nZW5vdWdoZm9yMjU2Yml0c2FsZ29yaXRobQ==

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashandhanushka16@gmail.com
spring.mail.password=lxmh msju hqmj qrut
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
